# Generated by Django 5.1.7 on 2025-03-07 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва послуги')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис послуги')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
            ],
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ПІБ майстра')),
                ('services', models.ManyToManyField(to='orders.service', verbose_name='Послуги')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100, verbose_name='ПІБ клієнта')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефону')),
                ('appointment_date', models.DateField(verbose_name='Дата запису')),
                ('appointment_time', models.TimeField(verbose_name='Час запису')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.master', verbose_name='Майстер')),
                ('services', models.ManyToManyField(to='orders.service', verbose_name='Обрані послуги')),
            ],
        ),
    ]
